-- 4-I (続き): T_BALANCE の外部キー（002 の前半が適用済みの環境向け）

ALTER TABLE T_BALANCE
  ADD CONSTRAINT fk_balance_customer
  FOREIGN KEY (CUSTOMER_ID) REFERENCES T_CUSTOMER (CUSTOMER_ID);

ALTER TABLE T_BALANCE
  ADD CONSTRAINT fk_balance_invoice
  FOREIGN KEY (INVOICE_ID) REFERENCES T_INVOICE (INVOICE_ID) ON DELETE CASCADE;

ALTER TABLE T_BALANCE
  ADD CONSTRAINT fk_balance_payment
  FOREIGN KEY (PAYMENT_ID) REFERENCES T_PAYMENT (PAYMENT_ID) ON DELETE CASCADE;

ALTER TABLE T_BALANCE
  ADD CONSTRAINT fk_balance_deposit
  FOREIGN KEY (DEPOSIT_ID) REFERENCES T_DEPOSIT (DEPOSIT_ID) ON DELETE CASCADE;
